[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Fallback for SPA - important for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
